### ISSUE TITLE
How to modify 1280 for different sized maps?

### ISSUE THREAD

**Issue by shinaka** [drmortalwombat/OscarTutorials#1]
Sorry to bug you again! I've been messing around with example 1280, but can't seem to get it rendering maps correctly if they aren't 16x16; I thought I modified things to get my map size working (30x30), but I'm clearly missing something. Thanks for any help you can provide! Sorry to keep pinging here - I looked for a project Discord and didn't see one!

**Comment by drmortalwombat** [comment]
The lines to look for are:
`const char * tm = PipeMap + (sy >> 2) * 16 + (sx >> 2);`
and
`tm += 16;`
I should have made a constant for this.

You can find me on the [Everything C64 Discord](https://discord.gg/ChvN59yqAF)
